Multiplex network service
trueos/trueos pull request #77
Opened 2018-06-07 15:00 UTC by beanpole135

Properly multiplex the network service and have it startup any device-specific services properly based on device config.

This fixes the issues we are seeing with dhcpcd/wpa_supplicant not getting started properly on bootup on many laptops, and also ensures that the service can be used to start/stop/restart network devices individually as needed.

2018-06-07 15:45 UTC, kmoore134 commented
This change scares me a bit. Right now we're doing a mostly "FreeBSD" thing where devd handles the starting of dhcpcd / wpa_supplicant on link-up (How FreeBSD rc.d works). This looks like it could cause weird race conditions now since network is going to try and start services and devd is going to also try to start them, possibly at same time...

2018-06-07 16:32 UTC, beanpole135 commented
The network service update avoids those race conditions by ensuring that it always starts *before* devd. This allows the init on-boot device setup to be handled by the meta-service, and after devd gets started then the individual hotplugged devices can be added/removed via devd events.

2018-06-07 20:24 UTC, kmoore134 requested changes
I'll need to perhaps investigate a bit more on the systems failing with the current implementation. This has a bunch of negative interactions with other services which we may not need to do since it worked perfectly fine with rc.d scripts and devd previously.

2018-06-07 20:24 UTC, kmoore134 commented on etc/init.d/network
> +  _conf=`sysrc -n ifconfig_${network_device}`
This is unnecessary. /etc/rc.conf and related files are sourced before init.d scripts are run. The environment variables should already be set. Check ifconfig_getargs() in network.subr

2018-06-07 20:24 UTC, kmoore134 commented on etc/init.d/network
> +	if [ "$RC_CMD" = "restart" ] || [ -n "${network_device}" ] ; then
This has potential to break other things such as hostap... Services that don't want to "destroy" the device shouldn't be using start/stop and instead use "restart" as FreeBSD does. The way this is written now, you can't destroy any specific device without destroying them *all* which would be a problem for FreeNAS / lagg, etc, etc.

2018-06-07 20:24 UTC, kmoore134 commented on etc/init.d/network
> +
I'm still investigating this. It's interaction with devd is going to be a problem going forward. Right now we assume devd is the source of truth when starting interfaces which aren't explicitly enabled, such as adding network.em0 to default runlevel manually.

2018-06-08 17:06 UTC, beanpole135 commented
ok, after a lot more work with Kris offline, I have a a finished set of changes to fix the issues we kept uncovering.
I am closing this pull request and will open a new PR for a "clean" view/test of this change.

2018-06-08 17:06 UTC, closed without merging